package com.pfe.predictive.core.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Persistent record of ML prediction results for audit trail and historical analysis.
 * Every call to the predictive maintenance ML service is logged here.
 * 
 * Used for:
 * - Prediction history queries (e.g., "Show RUL trend for machine X over 30 days")
 * - Audit trail of ML decisions
 * - Accuracy metrics calculation
 * - Dashboard charting and KPI calculations
 */
@Entity
@Table(name = "prediction_records", indexes = {
    @Index(name = "idx_prediction_machine_id", columnList = "machine_id"),
    @Index(name = "idx_prediction_timestamp", columnList = "predicted_at DESC"),
    @Index(name = "idx_prediction_machine_time", columnList = "machine_id, predicted_at DESC")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PredictionRecord {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Reference to the machine being predicted.
     * Foreign key to Machine entity.
     */
    @Column(name = "machine_id", nullable = false)
    private Long machineId;

    /**
     * Timestamp when prediction was generated by ML service.
     */
    @Column(name = "predicted_at", nullable = false)
    private LocalDateTime predictedAt;

    /**
     * Remaining Useful Life (RUL) in hours or cycles.
     * Represents the predicted time until machine failure.
     */
    @Column(name = "rul_value", nullable = false)
    private Double rulValue;

    /**
     * Lower bound of confidence interval (nullable).
     */
    @Column(name = "confidence_low")
    private Double confidenceLow;

    /**
     * Upper bound of confidence interval (nullable).
     */
    @Column(name = "confidence_high")
    private Double confidenceHigh;

    /**
     * Risk level classification derived from RUL value.
     * LOW: RUL > 7 days, MEDIUM: 3-7 days, HIGH: 1-3 days, CRITICAL: < 1 day
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", nullable = false)
    private RiskLevel riskLevel;

    /**
     * Version of the ML model used for prediction.
     * Retrieved from ML /model-info endpoint.
     */
    @Column(name = "model_version", length = 50)
    private String modelVersion;

    /**
     * Username of the user who triggered this prediction.
     */
    @Column(name = "triggered_by", length = 100)
    private String triggeredBy;

    /**
     * JSON snapshot of key input features used in prediction.
     * Used for debugging and audit purposes.
     * Typically contains first 5-10 key sensor readings.
     */
    @Column(name = "input_features_summary", columnDefinition = "TEXT")
    private String inputFeaturesSummary;

    /**
     * Timestamp of record creation (auto-managed).
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false, name = "created_date")
    private LocalDateTime createdDate;

    /**
     * Optimistic locking version.
     */
    @Version
    private Long version;
}
